FROM mcr.microsoft.com/playwright/python:v1.52.0-noble
WORKDIR /app
COPY pyproject.toml .
COPY src ./src
RUN pip install --no-cache-dir '.[playwright]'
COPY config ./config
RUN mkdir -p data secrets
EXPOSE 8000
CMD ["uvicorn","lemonde_full_rss.main:app","--host","0.0.0.0","--port","8000"]
